server:
  port: 8080
spring:
  application:
    name: test-microservice
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: latest
      group-id: test-group-id
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: com.example.demo.config.kafka.KafkaEventDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.example.demo.config.kafka.KafkaEventSerializer
#      properties:
#         interceptor.classes: ....KafkaLoggingProducerInterceptor
  data:
    mongodb:
      uri: mongodb://localhost:27017,localhost:27018,localhost:27019/test-kafka?replicaSet=rs0
demo:
  kafka:
    topic:
      payment: payment_topic
    group-id: kafka-group

